services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=data
